apiVersion: v2
name: myapp
description: My Python app
version: 1.0.0
appVersion: "1.0"

values:
  image:
    repository: my-registry/myapp
    tag: latest

  postgres:
    enabled: true
    postgresUser: myuser
    postgresPasswordSecret: myapp/postgres-password
    postgresDatabase: mydb

  redis:
    enabled: true

  app:
    env:
      - name: POSTGRES_USER
        value: myuser
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: myapp/postgres-password
            key: password
      - name: POSTGRES_DB
        value: mydb
      - name: REDIS_HOST
        value: redis
      - name: REDIS_PORT
        value: "6379"
    port: 8080
    logs:
      volumeMount:
        name: logs
        mountPath: /app/logs
    secrets:
      - name: myapp/github-creds

  secrets:
    - name: myapp/postgres-password
      type: Opaque
      data:
        password: <BASE64 ENCODED VALUE>

    - name: myapp/github-creds
      type: Opaque
      data:
        username: <BASE64 ENCODED VALUE>
        token: <BASE64 ENCODED VALUE>
