image:
  repository: docker.io/kuro112
  tag: casinoadmin

replicaCount: 3

nameOverride: ""
fullnameOverride: ""

service:
  name: app
  port: 443
  targetPort: 443

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: baohule.com
      paths:
        - path: /
          backend:
            serviceName: app
            servicePort: 443

podAnnotations:
  my-pod-annotation: example-value

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5

resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 0.5
    memory: 256Mi
