# Values for my Python app
image:
  repository: my-docker-repo/my-python-app
  tag: latest

# Redis configuration
redis:
  enabled: true
  image:
    repository: bitnami/redis
    tag: latest
  password: my-redis-password
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi

# Postgres configuration
postgresql:
  enabled: true
  postgresqlUsername: my-postgres-user
  postgresqlPassword: my-postgres-password
  postgresqlDatabase: my-postgres-database
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /my-python-app
  hosts:
    - host: my-python-app.example.com
      paths:
        - /my-python-app