ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: my-domain.com
      paths:
        - path: /
          backend:
            serviceName: my-service
            servicePort: 80

service:
  name: my-service
  port: 8000
  targetPort: 8000

image:
  repository: my-repo/my-app
  tag: 1.0

replicaCount: 3

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: my-serviceaccount