apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: my-release
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 8000
      protocol: TCP
  selector:
    app: app
