apiVersion: v1
kind: Service
metadata:
  name: {{ include "AdminHelm.fullname" . }}-service
  labels:
    app.kubernetes.io/name: {{ include "AdminHelm.name" . }}
    helm.sh/chart: {{ include "AdminHelm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "AdminHelm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
